name: Test pin actions using action commit map

on:
  push:
    branches: [ main ]

jobs:
  upload-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@cf3f51a67d2820f7a7cefa0831889fbbef41ca57 # v5.4.1
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24 # v5.4.3

      # - name: testing 
      #   uses: vamshi/hello@4.9
        
